dataset:
  train_path: "/media/gwendal/Data/Datasets/Dexed_split/train/"
  valid_path: "/media/gwendal/Data/Datasets/Dexed_split/valid/"
  test_path: "/media/gwendal/Data/Datasets/Dexed_split/test/"
  audio: "audio/"
  pitch: "pitch/"
  loudness: "loudness/"
  timbre: "timbre/"  # TODO set to empty before commit
  timbre_features: 'ac_hardness;ac_warmth;tt_SpecCrest_med;tt_SpecCrest_IQR;tt_SpecRollOff_med;tt_SpecRollOff_IQR;tt_SpecFlat_med;tt_SpecFlat_IQR;tt_SpecVar_med;tt_SpecVar_IQR;tt_OddEvenRatio_med;tt_OddEvenRatio_IQR'

common:
  sampling_rate: 16000
  block_size: 160  # 10ms frames  //  400 frames total. Original DDSP uses 4ms frames (1000 frames total)
  duration_secs: 4

model:
  name: "12AR_gamma0.5"
  synth_mode: "harmonic"  # harmonic or wavetable
  n_mfcc: 30
  hidden_size: 512
  n_harmonic: 100
  n_bands: 65
  n_wavetables: 20
  n_wt_pure_harmonics: 5
  upsampling_mode: "nearest"  # from time frames to audio rate. linear seems to impair training
  device: "cuda:0"

train:
  root_logs_dir: "/media/gwendal/Data/Logs/neural-synths-morph/DDSPdev2"
  batch_size: 48
  scales: [4096, 2048, 1024, 512, 256, 128]
  overlap: .75
  loss: 'lin+log'  # Only linear MSS loss (lin), or linear+logarithmic (lin+log)
  start_lr: 0.0015
  stop_lr: 0.00015
  epochs: 100
  plot_period_epochs: 5

test:
  batch_size: 2
  scales: [4096, 2048, 1024, 512, 256, 128]
  overlap: .75

crepe:
  model: "large"

visualize: false
